# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0c7257cf9c08d943c3ce85ccd2aead612a0af5c2e8332f58f775204cf805ddfbef9677211a9aa6f1786f052621f3b67d61400de9bfc0a4f75e5bea0c3a81bf03

test:
  secret_key_base: ee022a972ec40668880bc887a9c4b892065930fb68318a695dd34b6c48e4b437799635caaa6101d7d76fc3bc2fd36cfa36883803ed645f7becac12500b663cb1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
